const translations = {
    en: {
        welcomeEarlyMorning: "☀️ Rise & shine! Ready for some fresh beats?",
        welcomeMorningPeak: "🌅 Good morning! Your morning energy is peaking",
        welcomeLateMorning: "🎵 Morning vibes! Time for your daily soundtrack",
        welcomeNoon: "🌤️ Good noon! Lunch break melodies?",
        welcomeAfternoon: "☕ Good afternoon! Keep the rhythm flowing",
        welcomeEarlyEvening: "🌆 Good evening! Wind down with some tunes",
        welcomeEvening: "✨ Good evening! Your musical journey continues",
        welcomeLateNight: "🌙 Late night session? Let the music speak",
        welcomeMidnight: "🕛 Midnight melodies... find your peace",
        welcomeDeepNight: "⭐ Deep night vibes... just you and the music",

        navArtistsText: "Artists",
        githubBtnText: "Star on GitHub",
        profileName: "KORAI Personal Space",
        profileBio: "Sleek and minimalist local audio player & manager.",
        langBtnText: "FA",
        menuTitle: "Playlists Library",
        navHomeText: "Home",
        navLibText: "My Library",
        navFavText: "Favorites",
        navStatsText: "Live Telemetry",
        navAdvSearch: "Advanced Search",
        
        aiPanelTitle: "Acoustic AI",
        aiPanelDesc: "Analyzes dynamic frequency footprints, tempo, and harmonic energy to discover matching vibes.",
        aiBtnText: "Analyze Waveform",
        similarPlaylist: "Generate Smart Playlist",
        exportLibrary: "Export Library",
        importCue: "Import CUE Sheet",
        
        upTextTitle: "Import Audio File",
        upTextSub: "Add single local track",
        upFolderTitle: "Scan Audio Folder",
        upFolderSub: "Bulk import entire directory",
        upUrlTitle: "Stream from Link",
        upUrlSub: "Direct URL capture",
        
        loadingText: "Configuring KORAI Audio Core...",
        welcomeMorning: "Good Morning",
        welcomeAfternoon: "Good Afternoon",
        welcomeEvening: "Good Evening",
        
        emptyLibrary: "Your Library is Empty",
        emptyLibraryDesc: "Use the import options on the sidebar to add your local audio tracks.",
        emptyFavs: "No Favorites Yet",
        emptyFavsDesc: "Like your favorite songs to see them grouped here.",
        emptyArtistsState: "No Artists Found",
        emptyArtistsDesc: "Add some music tracks to see your artists.",
        
        statsTitle: "Playback Analytics & Stats",
        statsTotal: "Total Tracks",
        statsPlays: "Total Playbacks",
        statsLikes: "Liked Tracks",
        statsHero: "Most Played Masterpiece",
        totalTracksLabel: "Total Loaded Tracks",
        totalPlaysLabel: "Cumulative Playbacks",
        noTrackPlaying: "No track playing",
        extractionInProgress: "Extraction already in progress",
        preparingExtraction: "Preparing vocal extraction...",
        extractingVocal: "Separating vocals...",
        addingToLibrary: "Adding to library...",
        extractionComplete: "Extraction complete!",
        vocalTrackAdded: "Vocal track added",
        extractionNoTrack: "Track added but could not play automatically",
        extractionFailed: "Extraction failed",
        popularLabel: "Loved Tracks",
        topTrackLabel: "Your top music based on execution telemetry",
        liveSpectrumLabel: "Live Spectrum Telemetry Analyzer",
        statsError: "Failed to retrieve analytics data from server",
        playedTimes: "plays",
        
        queuePanelTitle: "Active Play Queue",
        fsExitText: "Exit Immersive Stage",
        
        playlistModalTitle: "Create New Playlist",
        playlistPlaceholder: "Enter playlist name...",
        dialogConfirm: "Confirm",
        dialogCancel: "Cancel",
        createPlaylist: "Create Playlist",
        downloadModalTitle: "Download MP3 from Link",
        downloadPlaceholder: "Paste direct audio stream URL here...",
        downloadBtn: "Download & Import",
        
        searchPlaceholder: "Search songs, artists, albums...",
        rightClickTip: "Right-click on tracks to manage playlists",
        libraryArchive: "Music Library Archive",
        dailySuggestions: "Curated Daily Discoveries",
        
        welcomeOobeTitle: "Welcome to KORAI Stage",
        welcomeOobeSub: "Immersive local audio system designed for audiophiles",
        welcomeOobeGoalTitle: "Project Core",
        welcomeOobeGoalDesc: "A beautiful, modern, and completely free music player. Built to provide endless and powerful features, usable on all computers without any limitations. This project is ready for development and achieving greater goals.",
        welcomeOobeCreatorTitle: "The Craft",
        welcomeOobeCreatorDesc: "I am Behdad Kanaani, a teenage programmer and lover of music, AI, computer vision, and everything related to programming and computers. I have many projects; visit my GitHub to see them.",
        welcomeOobeBtn: "Initialize Studio Core",
        
        dspPreservePitch: "Preserve Pitch:",
        dspTitle: "Graphic Studio Equalizer",
        tempo: "Playback Tempo",
        
        vocalSeparatorMode: "Vocal Separator (Real-time Vocal Removal):",
        vocalSeparatorIntensity: "Vocal Removal Intensity",
        vocalSeparatorSensitivity: "Detection Sensitivity",
        vocalSeparatorSensitivityDesc: "Lower = more aggressive removal, Higher = preserves more instruments",
        vocalSeparatorActive: "🎤 Vocal Separator: AI Vocal Removal Active",
        vocalSeparatorDisabled: "Vocal Separator Disabled",
        vocalSeparatorError: "Vocal separator failed to initialize",
        vocalSeparatorFirstPlay: "Play a track first to enable Vocal Separator",
        
        eq60Hz: "Bass (60Hz)",
        eq230Hz: "Low Mid (230Hz)",
        eq910Hz: "Mid (910Hz)",
        eq4kHz: "High Mid (4kHz)",
        eq14kHz: "Treble (14kHz)",
        
        emptyPlaylistState: "This playlist is empty",
        emptyPlaylistTip: "Right-click on tracks in My Library to append them here.",
        
        bpmBadge: "BPM",
        energyBadge: "Energy Profile",
        noLyrics: "Lyrics not found in metadata container.",

        playPause: "Play/Pause",
        previousTrack: "Previous",
        nextTrack: "Next",
        shuffle: "Shuffle Mode",
        repeat: "Repeat Mode",
        volume: "Master Volume",
        
        sleepTimer: "Sleep Timer:",
        sleepOff: "Disabled",
        sleepMinutes: "Min",
        cancel: "Cancel Timer",
        
        dragNotify: "Analyzing dropped files...",
        dragSuccess: "tracks successfully imported!",
        dragError: "Failed to import dropped files.",
        
        genreDetected: "Identified Genre",
        smartRecommendations: "KORAI Dynamic Feed",
        backToHome: "Back to Dashboard",
        playlistCreated: "Dynamic playlist constructed successfully",
        noSimilarTracks: "No matching acoustic profiles found",
        analyzingAudio: "Decrypting audio patterns...",
        
        genreBlues: "Blues / Jazz Acoustic",
        genreClassical: "Classical / Orchestral",
        genrePop: "Vocal Pop / Indie",
        genreDance: "Electronic Dance / House",
        genreEDM: "Club EDM / Trance",
        genreDnB: "Drum & Bass / Kinetic",
        genreHipHop: "Hip Hop / Urban Beat",
        genreMetal: "Rock / Heavy Metal",
        genreElectronic: "Synthwave / Electronic",

        similarity: "Similarity",
        recommended: "Recommended",

        sortByLabel: "Sort By:",
        sortDateAdded: "Date Added",
        sortTitle: "Title",
        sortArtist: "Artist",
        sortBpm: "BPM",
        sortDuration: "Duration",
        allGenres: "All Genres",
        
        artistsTitle: "Artists",
        tracksCount: "tracks",
        playingArtist: "Playing",
        backToArtists: "Back to Artists",
        playArtist: "Play All",
        trackTitle: "Title",
        albumTitle: "Album",
        actions: "Actions",
        
        statsHero: "Most Played Track",
        
        loadingMusicLibrary: "Loading music library...",
        noResultsFound: "No results found",
        searchResults: "Search Results",
        
        updateAvailable: "Update Available!",
        updateLater: "Remind Later",
        downloadNow: "Download Now",
        newVersionAvailable: "A new version of KORAI Player is available!",
        currentVersionLabel: "Current version",
        newVersionLabel: "New version"
    },
    fa: {
        welcomeEarlyMorning: "☀️ طلوع کردی؟ وقت آهنگ‌های پرانرژیه!",
        welcomeMorningPeak: "🌅 صبح بخیر! انرژی صبحت توی اوجشه",
        welcomeLateMorning: "🎵 حوالی ظهر! وقت یه آهنگ خوبه",
        welcomeNoon: "🌤️ ظهر بخیر! با موسیقی ناهار رو مزه‌دار کن",
        welcomeAfternoon: "☕ عصر بخیر! ریتم رو حفظ کن",
        welcomeEarlyEarlyEvening: "🌆 عصر بهاره! با موسیقی آروم بگیر",
        welcomeEvening: "✨ شب بخیر! سفر موسیقیت ادامه داره",
        welcomeLateNight: "🌙 پاسی از شب... بذار موسیقی حرف بزنه",
        welcomeMidnight: "🕛 نیمه‌شب‌ها... آرامش رو با نت‌ها پیدا کن",
        welcomeDeepNight: "⭐ سحرگاهه... فقط تو و موسیقی",
        
        navArtistsText: "آرتیست‌ها",
        githubBtnText: "ستاره در گیت‌هاب",
        profileName: "کتابخانه شخصی KORAI",
        profileBio: "سیستم مدیریت و پخش هوشمند موسیقی محلی.",
        langBtnText: "EN",
        menuTitle: "لیست‌های پخش",
        navHomeText: "صفحه اصلی",
        navLibText: "کتابخانه من",
        navFavText: "مورد علاقه‌ها",
        navStatsText: "تله‌متری زنده",
        navAdvSearch: "جستجوی پیشرفته",
        
        aiPanelTitle: "هوش مصنوعی صوتی",
        aiPanelDesc: "تحلیل الگوهای فرکانسی، سرعت ضربان (BPM) و انرژی موج جاری برای کشف نواهای هم‌سو.",
        aiBtnText: "تحلیل سیگنال صوتی",
        similarPlaylist: "ساخت پلی‌لیست هم‌سبک",
        exportLibrary: "خروجی کتابخانه",
        importCue: "وارد کردن CUE Sheet",
        
        upTextTitle: "افزودن قطعه صوتی",
        upTextSub: "وارد کردن فایل تکی",
        upFolderTitle: "اسکن کامل پوشه",
        upFolderSub: "بارگذاری گروهی دایرکتوری",
        upUrlTitle: "استریم مستقیم از وب",
        upUrlSub: "دریافت آنلاین پیوند MP3",
        
        loadingText: "در حال پیکربندی موتور صوتی KORAI...",
        welcomeMorning: "صبح بخیر",
        welcomeAfternoon: "ظهر بخیر",
        welcomeEvening: "عصر بخیر",
        
        emptyLibrary: "کتابخانه موسیقی شما خالی است",
        emptyLibraryDesc: "جهت افزودن آهنگ، از گزینه‌های پنل مدیریت سایدبار استفاده نمایید.",
        emptyFavs: "لیست علاقه‌مندی‌ها خالی است",
        emptyFavsDesc: "آهنگ‌های محبوب خود را لایک کنید تا در این بخش طبقه‌بندی شوند.",
        emptyArtistsState: "هیچ آرتیستی یافت نشد",
        emptyArtistsDesc: "برای مشاهده آرتیست‌ها، آهنگ‌های موسیقی اضافه کنید.",
        
        statsTitle: "آمار و تله‌متری پخش",
        statsTotal: "کل آهنگ‌ها",
        statsPlays: "دفعات پخش",
        statsLikes: "محبوب‌ترین‌ها",
        statsHero: "شاهکار صدر جدول پخش شما",
        totalTracksLabel: "کل قطعات بارگذاری شده",
        totalPlaysLabel: "کل دفعات پخش ثبت شده",
        popularLabel: "آثار مورد علاقه",
        topTrackLabel: "این اثر بر اساس تله‌متری سیستم پخش شما در صدر قرار دارد",
        liveSpectrumLabel: "تحلیلگر زنده طیف فرکانسی",
        statsError: "خطا در دریافت اطلاعات آمار از سرور اصلی",
        playedTimes: "بار پخش",
        
        queuePanelTitle: "صف پخش جاری فعال",
        fsExitText: "خروج از استیج سینمایی",
        
        playlistModalTitle: "ایجاد لیست پخش جدید",
        playlistPlaceholder: "نام پلی‌لیست را وارد کنید...",
        dialogConfirm: "تایید",
        dialogCancel: "انصراف",
        createPlaylist: "ایجاد لیست پخش",
        downloadModalTitle: "دانلود فایل صوتی از لینک",
        downloadPlaceholder: "آدرس لینک مستقیم استریم MP3 را وارد کنید...",
        downloadBtn: "دانلود و بارگذاری",
        
        searchPlaceholder: "جستجوی آهنگ، خواننده، آلبوم...",
        rightClickTip: "برای مدیریت و افزودن آهنگ‌ها به پلی‌لیست راست‌کلیک کنید",
        libraryArchive: "آرشیو جامع کتابخانه موسیقی",
        dailySuggestions: "پیشنهادهای هوشمند روزانه",
        
        welcomeOobeTitle: "به استیج KORAI خوش آمدید",
        welcomeOobeSub: "سیستم صوتی بومی و سینمایی طراحی شده برای علاقه‌مندان به موسیقی تراز اول",
        welcomeOobeGoalTitle: "هسته پروژه",
        welcomeOobeGoalDesc: "پلیر موسیقی زیبا، مدرن و کاملاً رایگان. ساخته شده برای ارائه امکانات بی‌پایان و خفن، قابل استفاده روی تمام کامپیوترها بدون هیچ محدودیتی. این پروژه آماده توسعه و دستیابی به اهداف بزرگ‌تر است.",
        welcomeOobeCreatorTitle: "توسعه و هنر",
        welcomeOobeCreatorDesc: "من بهداد کنعانی هستم، یک نوجوان برنامه‌نویس و عاشق موسیقی، هوش مصنوعی، بینایی کامپیوتر و هر چیزی که به برنامه‌نویسی و کامپیوتر ربط داشته باشد. پروژه‌های زیادی دارم؛ برای دیدن آن‌ها به گیت‌هاب من سر بزنید.",
        welcomeOobeBtn: "راه‌اندازی هسته صوتی کلاینت",
        
        dspPreservePitch: "حفظ گام صدا (Preserve Pitch):",
        dspTitle: "اکولایزر گرافیکی استودیویی",
        tempo: "سرعت پخش (تمپو)",
        
        vocalSeparatorMode: "جدا ساز صدای خواننده (حذف بلادرنگ صدای خواننده):",
        vocalSeparatorIntensity: "شدت حذف صدای خواننده",
        vocalSeparatorSensitivity: "حساسیت تشخیص",
        vocalSeparatorSensitivityDesc: "مقدار کمتر = حذف تهاجمی‌تر، مقدار بیشتر = حفظ بیشتر سازها",
        vocalSeparatorActive: "🎤 جدا ساز صدای خواننده: حذف هوشمند صدای خواننده فعال شد",
        vocalSeparatorDisabled: "جدا ساز صدای خواننده غیرفعال شد",
        vocalSeparatorError: "خطا در راه‌اندازی جدا ساز صدای خواننده",
        vocalSeparatorFirstPlay: "برای فعال‌سازی جدا ساز صدای خواننده ابتدا یک آهنگ پخش کنید",
        
        eq60Hz: "بیس (60Hz)",
        eq230Hz: "میانی پایین (230Hz)",
        eq910Hz: "میانی (910Hz)",
        eq4kHz: "میانی بالا (4kHz)",
        eq14kHz: "زیر (14kHz)",
        
        emptyPlaylistState: "این لیست پخش خالی است",
        emptyPlaylistTip: "در بخش «کتابخانه من» با راست‌کلیک روی آهنگ‌ها، آن‌ها را به این لیست اضافه کنید.",
        
        bpmBadge: "ضربان در دقیقه",
        energyBadge: "نمایه انرژی",
        noLyrics: "متن شعر در کانتینر متادیتای صوتی یافت نشد.",

        playPause: "پخش/توقف",
        previousTrack: "قبلی",
        nextTrack: "بعدی",
        shuffle: "پخش تصادفی",
        repeat: "تکرار",
        volume: "بلندی صدا",
        
        sleepTimer: "تایمر خواب:",
        sleepOff: "غیرفعال",
        sleepMinutes: "دقیقه",
        cancel: "لغو تایمر",
        
        dragNotify: "در حال بررسی و تحلیل فایل‌های صوتی رها شده...",
        dragSuccess: "قطعه جدید با موفقیت به آرشیو افزوده شد!",
        dragError: "خطا در پردازش فایل‌های صوتی رها شده.",
        
        genreDetected: "سبک شناسایی شده",
        smartRecommendations: "پیشنهادهای داینامیک KORAI",
        backToHome: "بازگشت به پیشخوان",
        playlistCreated: "لیست پخش هم‌نمایه با موفقیت ایجاد شد",
        noSimilarTracks: "هیچ نمایه فرکانسی مشابهی در کتابخانه یافت نشد",
        analyzingAudio: "رمزگشایی از الگوهای صوتی...",
        
        genreBlues: "بلوز / جاز آکوستیک",
        genreClassical: "کلاسیک / ارکسترال",
        genrePop: "پاپ / ایندی",
        genreDance: "الکترونیک دنس / هاوس",
        genreEDM: "کلاب EDM / ترنس",
        genreDnB: "درام اند بیس / پرانرژی",
        genreHipHop: "هیپ هاپ / اوربان بیت",
        genreMetal: "راک / هوی متال",
        genreElectronic: "سینث‌ویو / الکترونیک",

        similarity: "شباهت",
        recommended: "توصیه شده",

        sortByLabel: "مرتب‌سازی بر اساس:",
        sortDateAdded: "تاریخ اضافه شدن",
        sortTitle: "عنوان آهنگ",
        sortArtist: "خواننده",
        sortBpm: "ضربان (BPM)",
        sortDuration: "مدت زمان",
        allGenres: "همه سبک‌ها",
        
        artistsTitle: "آرتیست‌ها",
        tracksCount: "آهنگ",
        playingArtist: "در حال پخش",
        backToArtists: "بازگشت به آرتیست‌ها",
        playArtist: "پخش همه",
        trackTitle: "عنوان",
        albumTitle: "آلبوم",
        actions: "عملیات",
        
        statsHero: "پربازدیدترین آهنگ",
        
        loadingMusicLibrary: "در حال بارگذاری کتابخانه موسیقی...",
        noResultsFound: "نتیجه‌ای یافت نشد",
        searchResults: "نتایج جستجو",
        
        updateAvailable: "نسخه جدید موجود است!",
        updateLater: "یادآوری بعداً",
        downloadNow: "دانلود الآن",
        newVersionAvailable: "نسخه جدید KORAI Player منتشر شده است!",
        currentVersionLabel: "نسخه فعلی",
        newVersionLabel: "نسخه جدید",
        noTrackPlaying: "هیچ آهنگی در حال پخش نیست",
        extractionInProgress: "استخراج در حال انجام است",
        preparingExtraction: "آماده‌سازی برای استخراج...",
        extractingVocal: "در حال جدا سازی صدای خواننده...",
        addingToLibrary: "افزودن به کتابخانه...",
        extractionComplete: "استخراج کامل شد!",
        vocalTrackAdded: "آهنگ صدا اضافه شد",
        extractionNoTrack: "آهنگ اضافه شد اما پخش خودکار انجام نشد",
        extractionFailed: "خطا در استخراج"
    }
};