const translations = {
    en: {
        // ===== Time-based greetings =====
        welcomeEarlyMorning: "Rise & shine! Ready for some fresh beats?",
        welcomeMorningPeak: "Good morning! Your morning energy is peaking",
        welcomeLateMorning: "Morning vibes! Time for your daily soundtrack",
        welcomeNoon: "Good noon! Lunch break melodies?",
        welcomeAfternoon: "Good afternoon! Keep the rhythm flowing",
        welcomeEarlyEvening: "Good evening! Wind down with some tunes",
        welcomeEvening: "Good evening! Your musical journey continues",
        welcomeLateNight: "Late night session? Let the music speak",
        welcomeMidnight: "Midnight melodies... find your peace",
        welcomeDeepNight: "⭐ Deep night vibes... just you and the music",

        // ===== Navigation & Sidebar =====
        navHomeText: "Home",
        navLibText: "My Library",
        navArtistsText: "Artists",
        navAlbumsText: "Albums",
        navFavText: "Favorites",
        navStatsText: "Live Telemetry",
        navAdvSearch: "Advanced Search",
        navSettingsText: "Settings",
        navExplorerText: "Explorer",
        navPluginsText: "Plugins",
        githubStar: "Star on GitHub",
        readyToPlay: "Ready to Play",
        untitled: "Untitled",
        unknownArtist: "Unknown Artist",
        unknownAlbum: "Unknown Album",
        selectTrack: "Select a track",
        miniPlayerName: "KORAI Player",
        appTitle: "KORAI Music Player",
        returnToPlayer: "Return to main player",
        nowPlaying: "Now playing",
        nothingPlaying: "Nothing playing",
        chooseTrack: "Choose a track from your library",
        importFirstTrack: "Import your first track",
        addToPlaylist: "Add to playlist",
        cinematicStage: "KORAI Cinematic Stage",
        analyzingLyrics: "Analyzing lyrics in track metadata...",
        systemWarning: "System warning",
        confirmProceed: "Are you sure you want to proceed?",
        openQueue: "Open play queue",
        openMiniPlayer: "Open mini player",
        openDsp: "Open DSP Studio",
        preferredGenre: "Preferred genre",
        previousTrackAria: "Previous track",
        nextTrackAria: "Next track",
        playOrPause: "Play or pause",
        trackProgress: "Track progress",
        muteUnmute: "Mute or unmute",
        immersivePlayer: "Immersive player",
        songInfoVocal: "Song info and vocal extraction",
        likeTrack: "Like track",
        unlikeTrack: "Remove from favorites",
        closeDsp: "Close DSP Studio",
        dspProcessing: "Audio processing",
        playbackSection: "Playback",
        motionTransition: "Motion & transition",
        preservePitch: "Preserve pitch",
        preservePitchDesc: "Keep vocals natural when tempo changes",
        gaplessPlayback: "Gapless playback",
        gaplessPlaybackDesc: "Reduce silence between consecutive tracks",
        equalizer: "Equalizer",
        graphicStudio: "Graphic Studio",
        reset: "Reset",
        songInfo: "Song Info",
        close: "Close",
        extractVocalNewTrack: "Extract vocal (new track)",
        libraryOverview: "Library overview",
        quickAccess: "Quick access",
        playDiscoverOrganize: "Play • Discover • Organize",
        hoursListened: "Hours listened",
        aiMix: "AI Mix",
        continueListening: "Continue listening",
        resumeCurrentTrack: "Resume your current track",
        shuffleMix: "Shuffle mix",
        freshLibraryMix: "A fresh mix from your library",
        savedTracks: "saved tracks",
        browseAlbums: "Browse albums",
        albumsInLibrary: "albums in your library",
        moodEnergetic: "Energetic",
        moodChill: "Chill",
        moodFocus: "Focus",
        moodWorkout: "Workout",
        moodMelancholic: "Melancholic",
        moodHappy: "Happy",
        moodRomantic: "Romantic",
        moodStudy: "Study",
        moodBadge: "Mood",
        topEight: "Top 8",
        latest: "Latest",
        personalized: "Personalized",
        match: "match",
        off: "Off",
        morningSession: "Morning session",
        afternoonBeats: "Afternoon beats",
        eveningVibes: "Evening vibes",
        nightMode: "Night mode",
        goodMorning: "Good morning",
        goodAfternoon: "Good afternoon",
        goodEvening: "Good evening",
        goodNight: "Good night",
        readyToPlayQuestion: "Ready to play?",
        searchOnlineFailed: "Online search failed",
        homeViewAll: "View all",
        more: "More",
        recently: "Recently",

        // ===== Profile & Header =====
        githubBtnText: "Star on GitHub",
        profileName: "KORAI Personal Space",
        profileBio: "Sleek and minimalist local audio player & manager.",
        langBtnText: "FA",

        // ===== Playlists =====
        menuTitle: "Playlists Library",

        // ===== AI & Tools Panel =====
        aiPanelTitle: "Acoustic AI",
        aiPanelDesc: "Discover new tracks from the rhythm and frequency of your music.",
        aiBtnText: "Get AI recommendations",
        aiRecommendDesc: "Find tracks that match what you love.",
        similarPlaylist: "Smart Playlist",
        smartPlaylistDesc: "Build a playlist around this track.",
        exportLibrary: "Export Library",
        exportLibraryDesc: "Save your library as a CSV file.",
        importCue: "Import CUE",
        importCueDesc: "Import track markers from a CUE file.",

        // ===== Import Options =====
        upTextTitle: "Import Audio File",
        upTextSub: "Add single local track",
        upFolderTitle: "Scan Audio Folder",
        upFolderSub: "Bulk import entire directory",
        upUrlTitle: "Stream from Link",
        upUrlSub: "Direct URL capture",

        // ===== Splash & Loading =====
        loadingText: "Configuring KORAI Audio Core...",
        playerConnectionChecking: "Checking player connection...",
        playerConnected: "Connected to player",
        playerDisconnected: "Player disconnected",

        // ===== Empty States =====
        emptyLibrary: "Your Library is Empty",
        emptyLibraryDesc: "Use the import options on the sidebar to add your local audio tracks.",
        emptyFavs: "No Favorites Yet",
        emptyFavsDesc: "Like your favorite songs to see them grouped here.",
        emptyArtistsState: "No Artists Found",
        emptyArtistsDesc: "Add some music tracks to see your artists.",
        emptyAlbumsState: "No Albums Found",
        emptyAlbumsDesc: "Add music to see your albums.",
        emptyPlaylistState: "This playlist is empty",
        emptyPlaylistTip: "Right-click on tracks in My Library to append them here.",

        // ===== Statistics =====
        statsTitle: "Playback Analytics & Stats",
        liveTelemetryLabel: "LIVE TELEMETRY",
        telemetryDescription: "A live snapshot of your listening activity and library.",
        telemetrySpectrumDescription: "Watch the frequency response of the audio playing right now.",
        telemetryActive: "ANALYZER ACTIVE",
        telemetryWaiting: "WAITING FOR AUDIO",
        telemetryNoTopTrack: "No listening data yet",
        telemetryNoTopTrackHint: "Play a few tracks and your most-played favorite will show up here.",
        telemetryStartPlayback: "Start playback to see your live frequency spectrum",
        telemetryFrequency: "LIVE FREQUENCY",
        telemetryRealtime: "REAL-TIME AUDIO",
        statsTotal: "Total Tracks",
        statsPlays: "Total Playbacks",
        statsLikes: "Liked Tracks",
        statsHero: "Most Played Masterpiece",
        totalTracksLabel: "Total Loaded Tracks",
        totalPlaysLabel: "Cumulative Playbacks",
        popularLabel: "Loved Tracks",
        topTrackLabel: "Your top music based on your listening activity",
        liveSpectrumLabel: "Live Spectrum Telemetry Analyzer",
        statsError: "Failed to retrieve analytics data from server",
        playedTimes: "plays",

        // ===== Queue =====
        queuePanelTitle: "Active Play Queue",

        // ===== Fullscreen Player =====
        fsExitText: "Exit Immersive Stage",

        // ===== Modals =====
        playlistModalTitle: "Create New Playlist",
        playlistPlaceholder: "Enter playlist name...",
        dialogConfirm: "Confirm",
        dialogCancel: "Cancel",
        createPlaylist: "Create Playlist",
        downloadModalTitle: "Download MP3 from Link",
        downloadPlaceholder: "Paste direct audio stream URL here...",
        downloadBtn: "Download & Import",

        // ===== Search & Library =====
        searchPlaceholder: "Search songs, artists, albums...",
        rightClickTip: "Right-click on tracks to manage playlists",
        libraryArchive: "Music Library Archive",
        dailySuggestions: "Curated Daily Discoveries",

        // ===== Welcome / OOBE =====
        welcomeOobeTitle: "Welcome to KORAI Stage",
        welcomeOobeSub: "Immersive local audio system designed for audiophiles",
        welcomeOobeGoalTitle: "Project Core",
        welcomeOobeGoalDesc: "A beautiful, modern, and completely free music player. Built to provide endless and powerful features, usable on all computers without any limitations. This project is ready for development and achieving greater goals.",
        welcomeOobeCreatorTitle: "The Craft",
        welcomeOobeCreatorDesc: "I am Behdad Kanaani, a teenage programmer and lover of music, AI, computer vision, and everything related to programming and computers. I have many projects; visit my GitHub to see them.",
        welcomeOobeBtn: "Initialize Studio Core",

        // ===== DSP & EQ =====
        dspTitle: "Graphic Studio Equalizer",
        dspPreservePitch: "Preserve Pitch:",
        tempo: "Playback Tempo",

        // ===== Vocal Separator =====
        vocalSeparatorMode: "Vocal Separator (Real-time Vocal Removal):",
        vocalSeparatorIntensity: "Vocal Removal Intensity",
        vocalSeparatorSensitivity: "Detection Sensitivity",
        vocalSeparatorSensitivityDesc: "Lower = more aggressive removal, Higher = preserves more instruments",
        vocalSeparatorActive: "Vocal Separator: AI Vocal Removal Active",
        vocalSeparatorDisabled: "Vocal Separator Disabled",
        vocalSeparatorError: "Vocal separator failed to initialize",
        vocalSeparatorFirstPlay: "Play a track first to enable Vocal Separator",

        // ===== EQ Bands =====
        eq60Hz: "Bass (60Hz)",
        eq230Hz: "Low Mid (230Hz)",
        eq910Hz: "Mid (910Hz)",
        eq4kHz: "High Mid (4kHz)",
        eq14kHz: "Treble (14kHz)",

        // ===== Track Info =====
        bpmBadge: "BPM",
        energyBadge: "Energy Profile",
        noLyrics: "Lyrics not found in metadata container.",
        trackTitle: "Title",
        albumTitle: "Album",
        album: "Album",
        lyrics: "Lyrics",
        filterByGenre: "Filter by Genre",
        playAll: "Play All",
        actions: "Actions",
        artist: "Artist",
        genre: "Genre",
        duration: "Duration",
        codec: "Codec",
        bitrate: "Bitrate",
        sampleRate: "Sample Rate",
        energy: "Energy",

        // ===== Playback Controls =====
        playPause: "Play/Pause",
        previousTrack: "Previous",
        nextTrack: "Next",
        shuffle: "Shuffle Mode",
        repeat: "Repeat Mode",
        repeatAll: "Repeat All",
        repeatOne: "Repeat One",
        stereo: "Stereo",
        mono: "Mono",
        volume: "Master Volume",

        // ===== Sleep Timer =====
        sleepTimer: "Sleep Timer:",
        sleepOff: "Disabled",
        sleepMinutes: "Min",
        cancel: "Cancel Timer",

        // ===== Drag & Drop =====
        dragNotify: "Analyzing dropped files...",
        dragSuccess: "tracks successfully imported!",
        dragError: "Failed to import dropped files.",

        // ===== Genres =====
        genreDetected: "Identified Genre",
        genreBlues: "Blues / Jazz Acoustic",
        genreChill: "Chill / LoFi / Relaxing",
        genreClassical: "Classical / Orchestral",
        genreAcoustic: "Acoustic / Folk",
        genrePop: "Vocal Pop / Indie",
        genreDance: "Electronic Dance / House",
        genreEDM: "Club EDM / Trance",
        genreDnB: "Drum & Bass / Kinetic",
        genreHipHop: "Hip Hop / Urban Beat",
        genreMetal: "Rock / Heavy Metal",
        genreElectronic: "Synthwave / Electronic",
        genreLatin: "Latin / Reggae / Tropical",

        // ===== AI / Recommendations =====
        smartRecommendations: "KORAI Dynamic Feed",
        backToHome: "Back to Dashboard",
        playlistCreated: "Dynamic playlist constructed successfully",
        noSimilarTracks: "No matching acoustic profiles found",
        analyzingAudio: "Decrypting audio patterns...",
        similarity: "Similarity",
        recommended: "Recommended",

        // ===== Library Sorting =====
        sortByLabel: "Sort By:",
        sortDateAdded: "Date Added",
        sortTitle: "Title",
        sortArtist: "Artist",
        sortBpm: "BPM",
        sortDuration: "Duration",
        allGenres: "All Genres",

        // ===== Artists =====
        artistsTitle: "Artists",
        artistsCollection: "YOUR MUSIC, YOUR ARTISTS",
        artistsDescription: "Explore the voices and collections behind your music.",
        uniqueArtists: "unique artists",
        artistSearchPlaceholder: "Search artists...",
        artistSearchEmpty: "No artists match your search.",
        tracksCount: "tracks",
        playingArtist: "Playing",
        backToArtists: "Back to Artists",
        playArtist: "Play All",

        // ===== Albums =====
        albumsTitle: "Albums",
        backToAlbums: "Back to Albums",
        playAlbum: "Play All",

        // ===== Favorites =====
        likedTracks: "Liked Tracks",
        totalPlays: "Total Plays",
        topLiked: "Top Liked",
        recentlyAdded: "Recently Added",
        favoritesCollection: "YOUR PERSONAL COLLECTION",
        favoritesDescription: "Every track you have saved, together in one place.",
        favoriteAddedNotice: "Added to favorites",
        favoriteRemovedNotice: "Removed from favorites",
        removeFavorite: "Remove from favorites",
        browseLibrary: "Explore your library",
        playTrackAction: "Play track",

        // ===== Vocal Extraction =====
        extractionInProgress: "Extraction already in progress",
        preparingExtraction: "Preparing vocal extraction...",
        extractingVocal: "Separating vocals...",
        addingToLibrary: "Adding to library...",
        extractionComplete: "Extraction complete!",
        vocalTrackAdded: "Vocal track added",
        extractionNoTrack: "Track added but could not play automatically",
        extractionFailed: "Extraction failed",
        noTrackPlaying: "No track playing",

        // ===== Settings Page (NEW) =====
        settingsTitle: "Settings",
        settingsSubtitle: "Configure your KORAI experience",

        // Navigation
        settingsNavPlayback: "Playback",
        settingsNavAudio: "Audio & EQ",
        settingsNavAppearance: "Appearance",
        settingsNavLibrary: "Library",
        settingsNavPlugins: "Plugins",
        settingsNavAI: "AI & Recommendations",
        settingsNavSystem: "System & Tray",
        settingsNavAdvanced: "Advanced",
        settingsBackToPlayer: "Back to Player",

        // Playback section
        playbackGapless: "Gapless Playback",
        playbackGaplessDesc: "Seamless transition between tracks",
        playbackCrossfade: "Crossfade Duration",
        playbackCrossfadeDesc: "Fade duration between tracks",
        playbackRepeatMode: "Default Repeat Mode",
        playbackRepeatModeDesc: "Repeat behavior when starting playback",
        playbackShuffleDefault: "Default Shuffle Mode",
        playbackShuffleDefaultDesc: "Enable shuffle by default",
        playbackResumeOnStart: "Resume on Start",
        playbackResumeOnStartDesc: "Continue playback from last position when launching",

        // Audio section
        audioDefaultVolume: "Default Volume",
        audioDefaultVolumeDesc: "Initial volume level",
        audioOutput: "Audio Output",
        audioOutputDesc: "Stereo or Mono output",
        audioEqPresets: "Equalizer Presets",
        audioEqFlat: "Flat",
        audioEqRock: "Rock",
        audioEqPop: "Pop",
        audioEqClassical: "Classical",
        audioEqBass: "Bass Boost",
        audioEqTreble: "Treble Boost",

        // Appearance section
        appearanceDirection: "Direction",
        appearanceDirectionDesc: "UI text direction",
        appearanceDirectionLTR: "LTR (English)",
        appearanceDirectionRTL: "RTL (Persian)",
        appearanceFontSize: "Font Size",
        appearanceFontSizeDesc: "Adjust text size",
        appearanceFontSizeSmall: "Small",
        appearanceFontSizeMedium: "Medium",
        appearanceFontSizeLarge: "Large",
        appearanceShowAlbumArt: "Show Album Art in Player",
        appearanceShowAlbumArtDesc: "Display cover art in the playback bar",

        // Library section
        libraryScanPath: "Default Scan Path",
        libraryScanPathDesc: "Folder to scan for music",
        libraryScanPathNotSet: "Not set",
        librarySelectFolder: "Select Folder",
        libraryFormats: "Supported Formats",
        libraryFormatsDesc: "Audio formats to scan",
        libraryAutoScan: "Auto-Scan on Startup",
        libraryAutoScanDesc: "Automatically scan library folder when launching",
        libraryMaxScanDepth: "Max Scan Depth",
        libraryMaxScanDepthDesc: "How deep to scan subfolders",

        // Plugins section
        pluginsAutoActivate: "Auto-Activate Critical Plugins",
        pluginsAutoActivateDesc: "Start essential plugins automatically",
        pluginsHotReload: "Hot-Reload for Development",
        pluginsHotReloadDesc: "Reload plugins automatically on file change",
        pluginsHookTimeout: "Hook Timeout",
        pluginsHookTimeoutDesc: "Timeout for plugin hook execution",
        pluginsMemory: "Max Memory per Plugin",
        pluginsMemoryDesc: "Memory limit for each plugin",

        // AI section
        aiEnable: "Enable AI Recommendations",
        aiEnableDesc: "Personalized track suggestions",
        aiDiscovery: "Discovery Mode",
        aiDiscoveryDesc: "Suggest new and unheard tracks",
        aiWeights: "Behavior Weights",
        aiWeightsDesc: "Adjust how each interaction affects recommendations",
        aiWeightLike: "Like",
        aiWeightPlay: "Play",
        aiWeightSkip: "Skip",
        aiWeightRepeat: "Repeat",
        aiWeightPlaylistAdd: "Playlist Add",
        aiDiversity: "Diversity Boost",
        aiDiversityDesc: "How much variety to include in recommendations",

        // System section
        systemStayInTray: "Stay in Tray on Close",
        systemStayInTrayDesc: "When enabled, closing the window keeps KORAI running in the system tray",
        systemTrayNotification: "Show Notification on Hide",
        systemTrayNotificationDesc: "Show a notification when minimized to tray",
        systemAutoUpdate: "Auto-Check Updates",
        systemAutoUpdateDesc: "Automatically check for new versions",
        systemUpdateInterval: "Update Check Interval",
        systemUpdateIntervalDesc: "How often to check for updates",
        systemUpdateInterval12h: "12 hours",
        systemUpdateInterval24h: "24 hours",
        systemUpdateInterval48h: "48 hours",
        systemUpdateIntervalWeekly: "Weekly",
        systemDataDirectory: "Data Directory",
        systemDataDirectoryDesc: "Location of your KORAI data",
        systemOpenDataDir: "Open",
        systemClearCache: "Clear Cache & Telemetry",
        systemClearCacheDesc: "Remove temporary files and performance logs",
        systemClearCacheBtn: "Clear",
        systemVersion: "Current Version",
        systemVersionDesc: "Your KORAI version",
        systemCheckUpdates: "Check for Updates",

        // Advanced section
        advancedPerformance: "Performance Mode",
        advancedPerformanceDesc: "Reduce animations and effects for better performance",
        advancedDebugLogs: "Show Logs in Console",
        advancedDebugLogsDesc: "Enable debug logging to developer console",
        advancedServerPort: "Server Port",
        advancedServerPortDesc: "Local API server port (read-only)",
        advancedResetAll: "Reset All Settings",
        advancedResetAllDesc: "Restore all settings to factory defaults. This cannot be undone.",
        advancedResetBtn: "Reset All",

        // Settings actions
        settingsSave: "Save Settings",
        settingsSaveStatus: "Saved!",
        settingsSaveFailed: "Failed to save",
        settingsToastError: "Failed to save: ",
        settingsToastSuccess: "Settings saved successfully!",
        settingsResetConfirm: "Are you sure you want to reset ALL settings to defaults?\nThis action cannot be undone!",
        settingsResetConfirm2: "Really? This will reset EQ, playback, and all preferences.",
        settingsDefaultLoading: "Using default settings",
        settingsLoaded: "Settings loaded",
        settingsPageTitle: "KORAI | Settings",
        settingsLoading: "Loading...",
        settingsUserData: "User Data",
        settingsCacheCleared: "Cache cleared successfully!",
        settingsCacheClearFailed: "Failed to clear cache",
        settingsUpdateUnavailable: "Update check is not available",
        settingsUpdateFailed: "Update check failed",
        settingsResetSuccess: "Settings reset successfully",
        settingsResetFailed: "Failed to reset settings",

        // Toast messages
        toastSuccess: "Success",
        toastError: "Error",
        toastInfo: "Info",
        toastWarning: "Warning",
        updateAvailable: "Update available",
        noUpdates: "No updates available",
        playingAlbum: "Playing album",
        tracks: "tracks",
        plays: "plays",
        notificationNoTrackPlaying: "No track is currently playing",
        notificationRepeatOff: "Repeat disabled",
        notificationRepeatOne: "Repeat One (single track)",
        notificationRepeatAll: "Repeat All (playlist)",
        notificationAudioRecovered: "Audio system recovered",
        notificationAudioSystemError: "Audio system error. Please restart the app.",
        notificationGaplessEnabled: "Gapless playback enabled",
        notificationGaplessDisabled: "Gapless playback disabled",
        notificationUnknownError: "Unknown error",
        notificationTrackChangeFailed: "Error changing track",
        notificationAudioFileUnavailable: "Audio file not found or access denied",
        notificationCrossfadeSet: "Crossfade set to {seconds} seconds",
        notificationSleepTimerSet: "Sleep timer set to {minutes} minutes.",
        notificationMetadataSaving: "Saving metadata...",
        notificationMetadataSaved: "Metadata saved successfully!",
        notificationMetadataSaveFailed: "Failed to save metadata",
        notificationCueParsing: "Parsing CUE sheet...",
        notificationCueTracksFound: "Found {count} tracks in CUE sheet",
        notificationCuePlaylistCreated: "Created playlist from CUE sheet",
        notificationCueNoTracks: "No valid tracks found in CUE sheet",
        notificationCueParseFailed: "Failed to parse CUE sheet",
        notificationLibraryExporting: "Exporting library...",
        notificationLibraryExported: "Library exported to: {path}",
        notificationExportFailed: "Export failed",
        notificationPlaylistDeleted: "Playlist deleted",
        notificationPlaylistDeleteFailed: "Error deleting playlist",
        notificationTrackRemovedFromPlaylist: "Track removed from playlist",
        notificationTrackRemoveFailed: "Error removing track from playlist",
        notificationTrackAddedToPlaylist: "Track added to playlist",
        notificationTrackAlreadyInPlaylist: "Track already in playlist",
        notificationTrackAddFailed: "Error adding to playlist",
        notificationUnsupportedFormat: "File format is not supported or the file is corrupted.",
        notificationTrackNotFound: "Track not found",
        notificationAudioPlaybackError: "Error playing audio: {error}",
        notificationNoTrackSelected: "No track selected",
        notificationPlaybackNeedsInteraction: "Playback requires user interaction first",
        notificationPlaybackFormatUnsupported: "Audio format not supported",
        notificationPlaybackFailed: "Playback failed: {error}",
        notificationTrackRemoved: "Track removed",
        notificationConnectionFailed: "Connection failed",
        notificationMoodActivated: "{mood} mode activated — {count} tracks",
        notificationNoMoodTracks: "No tracks found for {mood} mood",
        notificationPlayTrackFirst: "Play a track first",
        notificationAIAnalyzing: "AI analyzing your taste...",
        notificationNoAIRecommendations: "No AI recommendations yet. Listen to more music!",
        notificationAIRecommendationFailed: "AI recommendation failed",
        notificationFindingMusic: "Finding new music for you...",
        notificationNoDiscoveries: "No new discoveries found",
        notificationDiscoveryFailed: "Discovery failed",
        notificationSimilarPlaylistCreated: 'Playlist "{name}" created with {count} tracks',
        notificationNoSimilarTracks: "No similar tracks found",
        notificationFavoritesUpdateFailed: "Failed to update favorites",
        notificationElectronUnavailable: "Electron API not available",
        notificationTracksImported: "Successfully imported {count} tracks.",
        notificationImportFailed: "Import failed: {error}",
        notificationScanningFolder: "Scanning folder...",
        notificationNoAudioFiles: "No audio files found in the selected folder. Supported formats: MP3, WAV, OGG, M4A, FLAC",
        notificationInvalidUrl: "Please provide a valid URL",
        notificationConfiguringCloud: "Configuring cloud request...",
        notificationAudioDownloaded: "Audio downloaded successfully",
        notificationRequestFailed: "Request failed",
        notificationCloudCaptureAborted: "Cloud capture aborted",
        notificationPlaylistImporting: "Importing playlist...",
        notificationPlaylistImported: 'Playlist "{name}" imported with {count} tracks',
        notificationPlaylistImportFailed: "Import failed: {error}",
        notificationPlaylistImportError: "Import error",
        notificationDownloadUrlUnavailable: "Download URL not available",
        notificationNoAudioFilesInPath: "No audio files found in: {path}\nSupported: MP3, WAV, OGG, M4A, FLAC",
        notificationSystemImportFailed: "Error importing files opened from the system",
        notificationInitializationFailed: "Initialization failed",
        notificationDataPathUnavailable: "Data directory path is not available",
        notificationCannotOpenDirectory: "Cannot open directory",

        // Explorer Page
        explorerSearchPlaceholder: "Type a song, artist or album name...",
        explorerSearchBtn: "Search",
        explorerNoResults: "No results found",
        explorerSearchHint: "Ready to explore new sounds.",
        explorerSave: "Save",
        explorerSaved: "Saved",
        explorerImport: "Import",
        explorerLikedEmpty: "Your collection is empty",
        explorerLikedEmptyDesc: "Start exploring and save tracks you love.",
        explorerFreshDrops: "Fresh Drops",
        explorerFreshDropsDesc: "The hottest new releases and trending albums updated daily.",
        explorerFetching: "Fetching latest hits...",
        explorerComingSoon: "Coming Soon",
        explorerComingSoonDesc: "This section will be populated with live top charts shortly.",
        explorerBrandAttribution: "Downloads are sourced from MusicDel.",
        explorerBrand: "KORAI Explore",
        explorerBack: "Back to player",
        explorerTabExplore: "Explore",
        explorerTabDiscover: "Discover",
        explorerFavorites: "Favorites",
        explorerSearchTitle: "Search the universe",
        explorerSearchDesc: "Find tracks, artists, albums, and playlists in great quality.",
        explorerCollectionTitle: "Your collection",
        explorerMusicDelTitle: "MusicDel Engine",
        explorerMusicDelSubtitle: "Advanced multi-strategy search",
        explorerClose: "Close",
        explorerPlayPreview: "Play or preview",
        explorerSongs: "Songs",
        explorerAlbums: "Albums",
        explorerArtists: "Artists",
        explorerPlaylists: "Playlists",
        explorerFirstWord: "First Word",
        explorerYourSearch: "Your Search",
        explorerFullTitle: "Full Title",
        explorerNoResultsHint: "Check the spelling or try another keyword.",
        explorerSavedTracksCount: "{count} saved tracks",
        explorerResultsCount: "{count} results found",
        explorerTracksSelectedCount: "{count} tracks selected for discovery",
        explorerNoResultsInColumn: "No results found",
        explorerOnlineSearchUnavailable: "The online search service is unavailable.",
        explorerDownloadLinkMissing: "Download link not found on the track page.",
        explorerDownloadPageFailed: "Failed to fetch track page: {status}",
        explorerAddTrackFailed: "Failed to add track to library.",
        explorerDownloadShort: "DL...",
        explorerUnknownError: "Unknown error",
        explorerSearchDatabase: "Searching database...",
        explorerSearchFailed: "Search failed",
        explorerSearchFailedStatus: "Search failed ({status})",
        explorerDiscoveryFailedStatus: "Discovery failed ({status})",
        explorerServerResponseError: "Server responded with status: {status}",
        explorerSearchQueriesMissing: "No search queries available.",
        explorerAddedFavorite: "Added to favorites",
        explorerRemovedFavorite: "Removed from favorites",
        explorerRetry: "Retry",
        explorerDownloading: "Downloading...",
        explorerAddedLibrary: "Added to library.",
        explorerImportError: "An error occurred during import.",
        explorerCheckSpelling: "Check the spelling or try another keyword.",
        explorerSearchUnavailable: "Search unavailable",
        explorerTryLater: "Try again later or use MusicDel search.",
        explorerDiscoveryBuilding: "Building a discovery mix from your local listening history...",
        explorerNothingToDiscover: "Nothing new to discover yet",
        explorerPlayForDiscovery: "Play a few tracks in KORAI for a personalized discovery mix.",
        explorerDiscoveryWaiting: "Your discovery queue is waiting for more listening history.",
        explorerTracksSelected: "tracks selected for discovery",
        explorerDiscoveryUnavailable: "Discovery unavailable",
        explorerLocalServiceUnavailable: "The local recommendation service is unavailable.",
        explorerTryAfterPlayback: "Start playback in KORAI and try again.",

        // ===== Plugin Manager (plugins.html) =====
        pluginStudio: "Plugin Studio",
        pluginPageTitle: "KORAI | Plugin Studio",
        pluginSubtitle: "Extend KORAI with powerful modules and custom integrations",
        pluginTotal: "Total Plugins",
        pluginActive: "Active",
        pluginRunning: "Running",
        pluginSearch: "Search plugins by name or ID...",
        pluginInstall: "Install Plugin",
        pluginInstalled: "Installed Plugins",
        pluginPerformance: "Performance",
        pluginExit: "Exit to Player",
        pluginManagement: "Management",
        all: "All",
        pluginWorking: "Working...",
        pluginInstalling: "Installing plugin...",
        pluginTotalHooks: "Total Hooks",
        pluginErrors: "Errors",
        pluginAvgTime: "Avg Time/Hook",
        pluginStats: "Plugin Statistics",
        pluginName: "Plugin",
        pluginCalls: "Calls",
        pluginAvg: "Avg (ms)",
        pluginPerfFailed: "Failed to load performance data",
        pluginNoDescription: "No description provided.",
        pluginBuiltinCantUninstall: "This built-in plugin cannot be uninstalled",
        pluginUninstalling: "Uninstalling...",
        pluginId: "ID",
        pluginVersion: "Version",
        pluginPath: "Path",
        pluginLoadingPerf: "Loading performance data...",
        moodTitle: "Mood & Energy",
        aiRecommendTitle: "AI Recommendations",
        recentActivity: "Recently Added",
        pluginNoPlugins: "No plugins found",
        pluginInstallHint: "Install a plugin to extend KORAI's capabilities",
        pluginEnable: "Enable",
        pluginDisable: "Disable",
        pluginUninstall: "Uninstall",
        pluginDetails: "Details",
        pluginEnabled: "Active",
        pluginDisabled: "Inactive",
        pluginRunningBadge: "Running",
        pluginBuiltin: "Built-in",
        pluginUninstallConfirm: "Are you sure you want to uninstall this plugin? This action cannot be undone.",
        pluginUninstallSuccess: "Plugin uninstalled successfully",
        pluginUninstallFailed: "Uninstall failed",
        pluginToggleSuccess: "Plugin status changed",
        pluginToggleFailed: "Failed to change plugin status",
        pluginInstallSuccess: "Plugin installed successfully!",
        pluginInstallFailed: "Installation failed",
        pluginMissingPermissions: "Missing permissions",
        pluginLoadingFailed: "Failed to load plugins",
        pluginDevKit: "Developer Kit",
        pluginPerfDashboard: "Performance Dashboard"
    },
    fa: {
        // ===== Time-based greetings =====
        welcomeEarlyMorning: "طلوع کردی؟ وقت آهنگ‌های پرانرژیه!",
        welcomeMorningPeak: "صبح بخیر! انرژی صبحت توی اوجشه",
        welcomeLateMorning: "حوالی ظهر! وقت یه آهنگ خوبه",
        welcomeNoon: "ظهر بخیر! با موسیقی ناهار رو مزه‌دار کن",
        welcomeAfternoon: "عصر بخیر! ریتم رو حفظ کن",
        welcomeEarlyEvening: "عصر بهاره! با موسیقی آروم بگیر",
        welcomeEvening: "شب بخیر! سفر موسیقیت ادامه داره",
        welcomeLateNight: "پاسی از شب... بذار موسیقی حرف بزنه",
        welcomeMidnight: "نیمه‌شب‌ها... آرامش رو با نت‌ها پیدا کن",
        welcomeDeepNight: "⭐ سحرگاهه... فقط تو و موسیقی",

        // ===== Navigation & Sidebar =====
        navHomeText: "صفحه اصلی",
        navLibText: "کتابخانه من",
        navArtistsText: "آرتیست‌ها",
        navAlbumsText: "آلبوم‌ها",
        navFavText: "مورد علاقه‌ها",
        navStatsText: "تله‌متری زنده",
        navAdvSearch: "جستجوی پیشرفته",
        navSettingsText: "تنظیمات",
        navExplorerText: "کاوش",
        navPluginsText: "افزونه‌ها",
        githubStar: "ستاره دادن در گیت‌هاب",
        readyToPlay: "آماده پخش",
        untitled: "بدون عنوان",
        unknownArtist: "هنرمند ناشناس",
        unknownAlbum: "آلبوم ناشناس",
        selectTrack: "یک آهنگ انتخاب کنید",
        miniPlayerName: "پلیر KORAI",
        appTitle: "پخش‌کننده موسیقی KORAI",
        returnToPlayer: "بازگشت به پلیر اصلی",
        nowPlaying: "در حال پخش",
        nothingPlaying: "آهنگی در حال پخش نیست",
        chooseTrack: "یک آهنگ از کتابخانه انتخاب کنید",
        importFirstTrack: "اولین آهنگتان را وارد کنید",
        addToPlaylist: "افزودن به فهرست پخش",
        cinematicStage: "صحنه‌ی سینمایی KORAI",
        analyzingLyrics: "در حال بررسی متن ترانه در فراداده‌ی آهنگ...",
        systemWarning: "هشدار سیستم",
        confirmProceed: "از انجام این کار مطمئن هستید؟",
        openQueue: "باز کردن صف پخش",
        openMiniPlayer: "باز کردن مینی‌پلیر",
        openDsp: "باز کردن استودیوی DSP",
        preferredGenre: "سبک دلخواه",
        previousTrackAria: "آهنگ قبلی",
        nextTrackAria: "آهنگ بعدی",
        playOrPause: "پخش یا توقف",
        trackProgress: "میزان پیشرفت آهنگ",
        muteUnmute: "قطع یا وصل صدا",
        immersivePlayer: "پلیر سینمایی",
        songInfoVocal: "اطلاعات آهنگ و جداسازی وکال",
        likeTrack: "افزودن به موردعلاقه‌ها",
        unlikeTrack: "حذف از موردعلاقه‌ها",
        closeDsp: "بستن استودیوی DSP",
        dspProcessing: "پردازش صدا",
        playbackSection: "پخش",
        motionTransition: "سرعت و گذار",
        preservePitch: "حفظ زیروبمی صدا",
        preservePitchDesc: "حفظ صدای طبیعی وکال هنگام تغییر سرعت",
        gaplessPlayback: "پخش بدون وقفه",
        gaplessPlaybackDesc: "کاهش سکوت بین آهنگ‌های پیاپی",
        equalizer: "اکولایزر",
        graphicStudio: "استودیوی گرافیکی",
        reset: "بازنشانی",
        songInfo: "اطلاعات آهنگ",
        close: "بستن",
        extractVocalNewTrack: "جداسازی وکال (آهنگ جدید)",
        libraryOverview: "نمای کلی کتابخانه",
        quickAccess: "دسترسی سریع",
        playDiscoverOrganize: "پخش • کاوش • سازمان‌دهی",
        hoursListened: "ساعت موسیقی",
        aiMix: "میکس هوشمند",
        continueListening: "ادامه‌ی پخش",
        resumeCurrentTrack: "ادامه‌ی آهنگ فعلی",
        shuffleMix: "میکس تصادفی",
        freshLibraryMix: "میکسی تازه از کتابخانه",
        savedTracks: "آهنگ ذخیره‌شده",
        browseAlbums: "مرور آلبوم‌ها",
        albumsInLibrary: "آلبوم در کتابخانه",
        moodEnergetic: "پرانرژی",
        moodChill: "آرام",
        moodFocus: "تمرکز",
        moodWorkout: "ورزشی",
        moodMelancholic: "غمگین",
        moodHappy: "شاد",
        moodRomantic: "عاشقانه",
        moodStudy: "مطالعه",
        moodBadge: "حال‌وهوا",
        topEight: "۸ برتر",
        latest: "تازه‌ترین",
        personalized: "پیشنهاد شخصی",
        match: "همخوانی",
        off: "خاموش",
        morningSession: "موسیقی صبحگاهی",
        afternoonBeats: "ریتم بعدازظهر",
        eveningVibes: "حال‌وهوای عصر",
        nightMode: "حالت شب",
        goodMorning: "صبح بخیر",
        goodAfternoon: "بعدازظهر بخیر",
        goodEvening: "عصر بخیر",
        goodNight: "شب بخیر",
        readyToPlayQuestion: "آماده‌ی پخش هستید؟",
        searchOnlineFailed: "جستجوی آنلاین ناموفق بود",
        homeViewAll: "مشاهده همه",
        more: "بیشتر",
        recently: "تازه",

        // ===== Profile & Header =====
        githubBtnText: "ستاره در گیت‌هاب",
        profileName: "کتابخانه شخصی KORAI",
        profileBio: "سیستم مدیریت و پخش هوشمند موسیقی محلی.",
        langBtnText: "EN",

        // ===== Playlists =====
        menuTitle: "لیست‌های پخش",

        // ===== AI & Tools Panel =====
        aiPanelTitle: "هوش مصنوعی صوتی",
        aiPanelDesc: "آهنگ‌های تازه را بر اساس ریتم و فرکانس موسیقی خود کشف کنید.",
        aiBtnText: "پیشنهاد هوشمند آهنگ",
        aiRecommendDesc: "آهنگ‌های هم‌سلیقه با موسیقی خود را پیدا کنید.",
        similarPlaylist: "پلی‌لیست هوشمند",
        smartPlaylistDesc: "با الهام از این آهنگ، پلی‌لیست بسازید.",
        exportLibrary: "خروجی کتابخانه",
        exportLibraryDesc: "کتابخانه را به‌صورت فایل CSV ذخیره کنید.",
        importCue: "CUE Sheet",
        importCueDesc: "نشانگرهای آهنگ را از فایل CUE وارد کنید.",

        // ===== Import Options =====
        upTextTitle: "افزودن قطعه صوتی",
        upTextSub: "وارد کردن فایل تکی",
        upFolderTitle: "اسکن کامل پوشه",
        upFolderSub: "بارگذاری گروهی دایرکتوری",
        upUrlTitle: "استریم مستقیم از وب",
        upUrlSub: "دریافت آنلاین پیوند MP3",

        // ===== Splash & Loading =====
        loadingText: "در حال پیکربندی موتور صوتی KORAI...",
        playerConnectionChecking: "در حال بررسی اتصال پلیر...",
        playerConnected: "پلیر متصل است",
        playerDisconnected: "اتصال به پلیر برقرار نیست",

        // ===== Empty States =====
        emptyLibrary: "کتابخانه موسیقی شما خالی است",
        emptyLibraryDesc: "جهت افزودن آهنگ، از گزینه‌های پنل مدیریت سایدبار استفاده نمایید.",
        emptyFavs: "لیست علاقه‌مندی‌ها خالی است",
        emptyFavsDesc: "آهنگ‌های محبوب خود را لایک کنید تا در این بخش طبقه‌بندی شوند.",
        emptyArtistsState: "هیچ آرتیستی یافت نشد",
        emptyArtistsDesc: "برای مشاهده آرتیست‌ها، آهنگ‌های موسیقی اضافه کنید.",
        emptyAlbumsState: "هیچ آلبومی یافت نشد",
        emptyAlbumsDesc: "برای مشاهده آلبوم‌ها، موسیقی اضافه کنید.",
        emptyPlaylistState: "این لیست پخش خالی است",
        emptyPlaylistTip: "در بخش «کتابخانه من» با راست‌کلیک روی آهنگ‌ها، آن‌ها را به این لیست اضافه کنید.",

        // ===== Statistics =====
        statsTitle: "آمار و تله‌متری پخش",
        liveTelemetryLabel: "تله‌متری زنده",
        telemetryDescription: "نمای زنده‌ای از فعالیت شنیداری و وضعیت کتابخانه‌تان.",
        telemetrySpectrumDescription: "واکنش فرکانسی صدای در حال پخش را به‌صورت زنده ببینید.",
        telemetryActive: "تحلیلگر فعال است",
        telemetryWaiting: "در انتظار صدا",
        telemetryNoTopTrack: "هنوز داده‌ای از پخش نداریم",
        telemetryNoTopTrackHint: "چند آهنگ پخش کنید تا پرشنونده‌ترین آهنگتان اینجا نمایش داده شود.",
        telemetryStartPlayback: "برای دیدن طیف زنده، پخش یک آهنگ را شروع کنید",
        telemetryFrequency: "فرکانس زنده",
        telemetryRealtime: "صدای لحظه‌ای",
        statsTotal: "کل آهنگ‌ها",
        statsPlays: "دفعات پخش",
        statsLikes: "محبوب‌ترین‌ها",
        statsHero: "شاهکار صدر جدول پخش شما",
        totalTracksLabel: "کل قطعات بارگذاری شده",
        totalPlaysLabel: "کل دفعات پخش ثبت شده",
        popularLabel: "آثار مورد علاقه",
        topTrackLabel: "این اثر بر اساس تله‌متری سیستم پخش شما در صدر قرار دارد",
        liveSpectrumLabel: "تحلیلگر زنده طیف فرکانسی",
        statsError: "خطا در دریافت اطلاعات آمار از سرور اصلی",
        playedTimes: "بار پخش",

        // ===== Queue =====
        queuePanelTitle: "صف پخش جاری فعال",

        // ===== Fullscreen Player =====
        fsExitText: "خروج از استیج سینمایی",

        // ===== Modals =====
        playlistModalTitle: "ایجاد لیست پخش جدید",
        playlistPlaceholder: "نام پلی‌لیست را وارد کنید...",
        dialogConfirm: "تایید",
        dialogCancel: "انصراف",
        createPlaylist: "ایجاد لیست پخش",
        downloadModalTitle: "دانلود فایل صوتی از لینک",
        downloadPlaceholder: "آدرس لینک مستقیم استریم MP3 را وارد کنید...",
        downloadBtn: "دانلود و بارگذاری",

        // ===== Search & Library =====
        searchPlaceholder: "جستجوی آهنگ، خواننده، آلبوم...",
        rightClickTip: "برای مدیریت و افزودن آهنگ‌ها به پلی‌لیست راست‌کلیک کنید",
        libraryArchive: "آرشیو جامع کتابخانه موسیقی",
        dailySuggestions: "پیشنهادهای هوشمند روزانه",

        // ===== Welcome / OOBE =====
        welcomeOobeTitle: "به استیج KORAI خوش آمدید",
        welcomeOobeSub: "سیستم صوتی بومی و سینمایی طراحی شده برای علاقه‌مندان به موسیقی تراز اول",
        welcomeOobeGoalTitle: "هسته پروژه",
        welcomeOobeGoalDesc: "پلیر موسیقی زیبا، مدرن و کاملاً رایگان. ساخته شده برای ارائه امکانات بی‌پایان و خفن، قابل استفاده روی تمام کامپیوترها بدون هیچ محدودیتی. این پروژه آماده توسعه و دستیابی به اهداف بزرگ‌تر است.",
        welcomeOobeCreatorTitle: "توسعه و هنر",
        welcomeOobeCreatorDesc: "من بهداد کنعانی هستم، یک نوجوان برنامه‌نویس و عاشق موسیقی، هوش مصنوعی، بینایی کامپیوتر و هر چیزی که به برنامه‌نویسی و کامپیوتر ربط داشته باشد. پروژه‌های زیادی دارم؛ برای دیدن آن‌ها به گیت‌هاب من سر بزنید.",
        welcomeOobeBtn: "راه‌اندازی هسته صوتی کلاینت",

        // ===== DSP & EQ =====
        dspTitle: "اکولایزر گرافیکی استودیویی",
        dspPreservePitch: "حفظ گام صدا (Preserve Pitch):",
        tempo: "سرعت پخش (تمپو)",

        // ===== Vocal Separator =====
        vocalSeparatorMode: "جدا ساز صدای خواننده (حذف بلادرنگ صدای خواننده):",
        vocalSeparatorIntensity: "شدت حذف صدای خواننده",
        vocalSeparatorSensitivity: "حساسیت تشخیص",
        vocalSeparatorSensitivityDesc: "مقدار کمتر = حذف تهاجمی‌تر، مقدار بیشتر = حفظ بیشتر سازها",
        vocalSeparatorActive: "جدا ساز صدای خواننده: حذف هوشمند صدای خواننده فعال شد",
        vocalSeparatorDisabled: "جدا ساز صدای خواننده غیرفعال شد",
        vocalSeparatorError: "خطا در راه‌اندازی جدا ساز صدای خواننده",
        vocalSeparatorFirstPlay: "برای فعال‌سازی جدا ساز صدای خواننده ابتدا یک آهنگ پخش کنید",

        // ===== EQ Bands =====
        eq60Hz: "بیس (60Hz)",
        eq230Hz: "میانی پایین (230Hz)",
        eq910Hz: "میانی (910Hz)",
        eq4kHz: "میانی بالا (4kHz)",
        eq14kHz: "زیر (14kHz)",

        // ===== Track Info =====
        bpmBadge: "ضربان در دقیقه",
        energyBadge: "نمایه انرژی",
        noLyrics: "متن شعر در کانتینر متادیتای صوتی یافت نشد.",
        trackTitle: "عنوان",
        albumTitle: "آلبوم",
        album: "آلبوم",
        lyrics: "متن ترانه",
        filterByGenre: "دسته‌بندی بر اساس سبک",
        playAll: "پخش همه",
        actions: "عملیات",
        artist: "خواننده",
        genre: "سبک",
        duration: "مدت زمان",
        codec: "کدک",
        bitrate: "نرخ بیت",
        sampleRate: "نرخ نمونه‌برداری",
        energy: "انرژی",

        // ===== Playback Controls =====
        playPause: "پخش/توقف",
        previousTrack: "قبلی",
        nextTrack: "بعدی",
        shuffle: "پخش تصادفی",
        repeat: "تکرار",
        repeatAll: "تکرار همه",
        repeatOne: "تکرار یک آهنگ",
        stereo: "استریو",
        mono: "مونو",
        volume: "بلندی صدا",

        // ===== Sleep Timer =====
        sleepTimer: "تایمر خواب:",
        sleepOff: "غیرفعال",
        sleepMinutes: "دقیقه",
        cancel: "لغو تایمر",

        // ===== Drag & Drop =====
        dragNotify: "در حال بررسی و تحلیل فایل‌های صوتی رها شده...",
        dragSuccess: "قطعه جدید با موفقیت به آرشیو افزوده شد!",
        dragError: "خطا در پردازش فایل‌های صوتی رها شده.",

        // ===== Genres =====
        genreDetected: "سبک شناسایی شده",
        genreBlues: "بلوز / جاز آکوستیک",
        genreChill: "چیل / لوفای / آرام",
        genreClassical: "کلاسیک / ارکسترال",
        genreAcoustic: "آکوستیک / فولک",
        genrePop: "پاپ / ایندی",
        genreDance: "الکترونیک دنس / هاوس",
        genreEDM: "کلاب EDM / ترنس",
        genreDnB: "درام اند بیس / پرانرژی",
        genreHipHop: "هیپ هاپ / اوربان بیت",
        genreMetal: "راک / هوی متال",
        genreElectronic: "سینث‌ویو / الکترونیک",
        genreLatin: "لاتین / رگه / تروپیکال",

        // ===== AI / Recommendations =====
        smartRecommendations: "پیشنهادهای داینامیک KORAI",
        backToHome: "بازگشت به پیشخوان",
        playlistCreated: "لیست پخش هم‌نمایه با موفقیت ایجاد شد",
        noSimilarTracks: "هیچ نمایه فرکانسی مشابهی در کتابخانه یافت نشد",
        analyzingAudio: "رمزگشایی از الگوهای صوتی...",
        similarity: "شباهت",
        recommended: "توصیه شده",

        // ===== Library Sorting =====
        sortByLabel: "مرتب‌سازی بر اساس:",
        sortDateAdded: "تاریخ اضافه شدن",
        sortTitle: "عنوان آهنگ",
        sortArtist: "خواننده",
        sortBpm: "ضربان (BPM)",
        sortDuration: "مدت زمان",
        allGenres: "همه سبک‌ها",

        // ===== Artists =====
        artistsTitle: "آرتیست‌ها",
        artistsCollection: "موسیقی شما، آرتیست‌های شما",
        artistsDescription: "صداها و مجموعه‌های موسیقی خود را کاوش کنید.",
        uniqueArtists: "آرتیست منحصربه‌فرد",
        artistSearchPlaceholder: "جستجوی آرتیست...",
        artistSearchEmpty: "آرتیستی با این نام پیدا نشد.",
        tracksCount: "آهنگ",
        playingArtist: "در حال پخش",
        backToArtists: "بازگشت به آرتیست‌ها",
        playArtist: "پخش همه",

        // ===== Albums =====
        albumsTitle: "آلبوم‌ها",
        backToAlbums: "بازگشت به آلبوم‌ها",
        playAlbum: "پخش همه",

        // ===== Favorites =====
        likedTracks: "آهنگ‌های مورد علاقه",
        totalPlays: "کل پخش‌ها",
        topLiked: "محبوب‌ترین‌ها",
        recentlyAdded: "به‌تازگی اضافه شده",
        favoritesCollection: "مجموعه شخصی شما",
        favoritesDescription: "همه آهنگ‌هایی که ذخیره کرده‌اید، یک‌جا.",
        favoriteAddedNotice: "به موردعلاقه‌ها اضافه شد",
        favoriteRemovedNotice: "از موردعلاقه‌ها حذف شد",
        removeFavorite: "حذف از موردعلاقه‌ها",
        browseLibrary: "کاوش در کتابخانه",
        playTrackAction: "پخش آهنگ",

        // ===== Vocal Extraction =====
        extractionInProgress: "استخراج در حال انجام است",
        preparingExtraction: "آماده‌سازی برای استخراج...",
        extractingVocal: "در حال جدا سازی صدای خواننده...",
        addingToLibrary: "افزودن به کتابخانه...",
        extractionComplete: "استخراج کامل شد!",
        vocalTrackAdded: "آهنگ صدا اضافه شد",
        extractionNoTrack: "آهنگ اضافه شد اما پخش خودکار انجام نشد",
        extractionFailed: "خطا در استخراج",
        noTrackPlaying: "هیچ آهنگی در حال پخش نیست",

        // ===== Settings Page (NEW) =====
        settingsTitle: "تنظیمات",
        settingsSubtitle: "تجربه KORAI خود را پیکربندی کنید",

        // Navigation
        settingsNavPlayback: "پخش",
        settingsNavAudio: "صدا و اکولایزر",
        settingsNavAppearance: "ظاهر",
        settingsNavLibrary: "کتابخانه",
        settingsNavPlugins: "افزونه‌ها",
        settingsNavAI: "هوش مصنوعی و پیشنهادات",
        settingsNavSystem: "سیستم و سینی",
        settingsNavAdvanced: "پیشرفته",
        settingsBackToPlayer: "بازگشت به پلیر",

        // Playback section
        playbackGapless: "پخش بدون وقفه",
        playbackGaplessDesc: "انتقال یکپارچه بین آهنگ‌ها",
        playbackCrossfade: "مدت زمان محو شدن",
        playbackCrossfadeDesc: "مدت زمان محو شدن بین آهنگ‌ها",
        playbackRepeatMode: "حالت تکرار پیش‌فرض",
        playbackRepeatModeDesc: "رفتار تکرار هنگام شروع پخش",
        playbackShuffleDefault: "حالت تصادفی پیش‌فرض",
        playbackShuffleDefaultDesc: "فعال کردن پخش تصادفی به‌طور پیش‌فرض",
        playbackResumeOnStart: "ادامه پخش در شروع",
        playbackResumeOnStartDesc: "ادامه پخش از موقعیت آخرین بار هنگام راه‌اندازی",

        // Audio section
        audioDefaultVolume: "بلندی صدای پیش‌فرض",
        audioDefaultVolumeDesc: "سطح اولیه صدا",
        audioOutput: "خروجی صدا",
        audioOutputDesc: "خروجی استریو یا مونو",
        audioEqPresets: "پریست‌های اکولایزر",
        audioEqFlat: "مسطح",
        audioEqRock: "راک",
        audioEqPop: "پاپ",
        audioEqClassical: "کلاسیک",
        audioEqBass: "تقویت بیس",
        audioEqTreble: "تقویت زیر",

        // Appearance section
        appearanceDirection: "جهت",
        appearanceDirectionDesc: "جهت متن رابط کاربری",
        appearanceDirectionLTR: "چپ‌به‌راست (انگلیسی)",
        appearanceDirectionRTL: "راست‌به‌چپ (فارسی)",
        appearanceFontSize: "اندازه فونت",
        appearanceFontSizeDesc: "اندازه متن را تنظیم کنید",
        appearanceFontSizeSmall: "کوچک",
        appearanceFontSizeMedium: "متوسط",
        appearanceFontSizeLarge: "بزرگ",
        appearanceShowAlbumArt: "نمایش کاور آلبوم در پلیر",
        appearanceShowAlbumArtDesc: "نمایش کاور در نوار پخش",

        // Library section
        libraryScanPath: "مسیر اسکن پیش‌فرض",
        libraryScanPathDesc: "پوشه‌ای که برای موسیقی اسکن می‌شود",
        libraryScanPathNotSet: "تنظیم نشده",
        librarySelectFolder: "انتخاب پوشه",
        libraryFormats: "فرمت‌های پشتیبانی شده",
        libraryFormatsDesc: "فرمت‌های صوتی برای اسکن",
        libraryAutoScan: "اسکن خودکار در راه‌اندازی",
        libraryAutoScanDesc: "اسکن خودکار پوشه کتابخانه هنگام راه‌اندازی",
        libraryMaxScanDepth: "حداکثر عمق اسکن",
        libraryMaxScanDepthDesc: "عمق اسکن زیرپوشه‌ها",

        // Plugins section
        pluginsAutoActivate: "فعال‌سازی خودکار افزونه‌های حیاتی",
        pluginsAutoActivateDesc: "راه‌اندازی خودکار افزونه‌های ضروری",
        pluginsHotReload: "بارگذاری مجدد داغ برای توسعه",
        pluginsHotReloadDesc: "بارگذاری مجدد خودکار افزونه‌ها هنگام تغییر فایل",
        pluginsHookTimeout: "مهلت اجرای هوک",
        pluginsHookTimeoutDesc: "مهلت زمانی برای اجرای هوک افزونه",
        pluginsMemory: "حداکثر حافظه برای هر افزونه",
        pluginsMemoryDesc: "محدودیت حافظه برای هر افزونه",

        // AI section
        aiEnable: "فعال‌سازی پیشنهادات هوش مصنوعی",
        aiEnableDesc: "پیشنهادات شخصی‌سازی شده آهنگ",
        aiDiscovery: "حالت کشف",
        aiDiscoveryDesc: "پیشنهاد آهنگ‌های جدید و ناشنیده",
        aiWeights: "وزن‌های رفتاری",
        aiWeightsDesc: "تأثیر هر تعامل بر پیشنهادات را تنظیم کنید",
        aiWeightLike: "پسندیدن",
        aiWeightPlay: "پخش",
        aiWeightSkip: "پرش",
        aiWeightRepeat: "تکرار",
        aiWeightPlaylistAdd: "افزودن به لیست پخش",
        aiDiversity: "افزایش تنوع",
        aiDiversityDesc: "میزان تنوع در پیشنهادات",

        // System section
        systemStayInTray: "ماندن در سینی هنگام بستن",
        systemStayInTrayDesc: "هنگام فعال بودن، بستن پنجره KORAI را در سینی سیستم نگه می‌دارد",
        systemTrayNotification: "نمایش اعلان هنگام مخفی شدن",
        systemTrayNotificationDesc: "نمایش اعلان هنگام کوچک شدن به سینی",
        systemAutoUpdate: "بررسی خودکار به‌روزرسانی",
        systemAutoUpdateDesc: "بررسی خودکار نسخه‌های جدید",
        systemUpdateInterval: "فاصله بررسی به‌روزرسانی",
        systemUpdateIntervalDesc: "هر چند وقت یک‌بار به‌روزرسانی بررسی شود",
        systemUpdateInterval12h: "۱۲ ساعت",
        systemUpdateInterval24h: "۲۴ ساعت",
        systemUpdateInterval48h: "۴۸ ساعت",
        systemUpdateIntervalWeekly: "هفتگی",
        systemDataDirectory: "پوشه داده",
        systemDataDirectoryDesc: "محل ذخیره داده‌های KORAI",
        systemOpenDataDir: "باز کردن",
        systemClearCache: "پاک کردن حافظه نهان و تله‌متری",
        systemClearCacheDesc: "حذف فایل‌های موقت و لاگ‌های عملکرد",
        systemClearCacheBtn: "پاک کردن",
        systemVersion: "نسخه فعلی",
        systemVersionDesc: "نسخه KORAI شما",
        systemCheckUpdates: "بررسی به‌روزرسانی",

        // Advanced section
        advancedPerformance: "حالت عملکرد",
        advancedPerformanceDesc: "کاهش انیمیشن‌ها و افکت‌ها برای عملکرد بهتر",
        advancedDebugLogs: "نمایش لاگ‌ها در کنسول",
        advancedDebugLogsDesc: "فعال کردن لاگ‌های دیباگ در کنسول توسعه‌دهنده",
        advancedServerPort: "پورت سرور",
        advancedServerPortDesc: "پورت سرور API محلی (فقط خواندنی)",
        advancedResetAll: "بازنشانی همه تنظیمات",
        advancedResetAllDesc: "بازگرداندن همه تنظیمات به حالت پیش‌فرض کارخانه. این عمل قابل بازگشت نیست.",
        advancedResetBtn: "بازنشانی همه",

        // Settings actions
        settingsSave: "ذخیره تنظیمات",
        settingsSaveStatus: "ذخیره شد!",
        settingsSaveFailed: "ذخیره ناموفق",
        settingsToastError: "خطا در ذخیره: ",
        settingsToastSuccess: "تنظیمات با موفقیت ذخیره شد!",
        settingsResetConfirm: "آیا از بازنشانی همه تنظیمات به حالت پیش‌فرض مطمئن هستید؟\nاین عمل قابل بازگشت نیست!",
        settingsResetConfirm2: "واقعاً؟ این کار اکولایزر، پخش و همه تنظیمات را بازنشانی می‌کند.",
        settingsDefaultLoading: "استفاده از تنظیمات پیش‌فرض",
        settingsLoaded: "تنظیمات بارگذاری شد",
        settingsPageTitle: "KORAI | تنظیمات",
        settingsLoading: "در حال بارگذاری...",
        settingsUserData: "داده‌های کاربر",
        settingsCacheCleared: "حافظه نهان با موفقیت پاک شد!",
        settingsCacheClearFailed: "پاک‌کردن حافظه نهان ناموفق بود",
        settingsUpdateUnavailable: "بررسی به‌روزرسانی در دسترس نیست",
        settingsUpdateFailed: "بررسی به‌روزرسانی ناموفق بود",
        settingsResetSuccess: "تنظیمات با موفقیت بازنشانی شد",
        settingsResetFailed: "بازنشانی تنظیمات ناموفق بود",

        // Toast messages
        toastSuccess: "موفق",
        toastError: "خطا",
        toastInfo: "اطلاعات",
        toastWarning: "هشدار",
        updateAvailable: "به‌روزرسانی جدید موجود است",
        noUpdates: "به‌روزرسانی جدیدی موجود نیست",
        playingAlbum: "در حال پخش آلبوم",
        tracks: "آهنگ",
        plays: "بار پخش",
        notificationNoTrackPlaying: "در حال حاضر آهنگی پخش نمی‌شود",
        notificationRepeatOff: "تکرار غیرفعال شد",
        notificationRepeatOne: "تکرار یک آهنگ",
        notificationRepeatAll: "تکرار همه آهنگ‌ها",
        notificationAudioRecovered: "سیستم صوتی بازیابی شد",
        notificationAudioSystemError: "خطا در سیستم صوتی. لطفاً برنامه را دوباره راه‌اندازی کنید.",
        notificationGaplessEnabled: "پخش بدون وقفه فعال شد",
        notificationGaplessDisabled: "پخش بدون وقفه غیرفعال شد",
        notificationUnknownError: "خطای نامشخص",
        notificationTrackChangeFailed: "تغییر آهنگ ناموفق بود",
        notificationAudioFileUnavailable: "فایل صوتی پیدا نشد یا دسترسی به آن مجاز نیست",
        notificationCrossfadeSet: "مدت محوشدن متقاطع روی {seconds} ثانیه تنظیم شد",
        notificationSleepTimerSet: "زمان‌سنج خواب برای {minutes} دقیقه تنظیم شد.",
        notificationMetadataSaving: "در حال ذخیره فراداده...",
        notificationMetadataSaved: "فراداده با موفقیت ذخیره شد!",
        notificationMetadataSaveFailed: "ذخیره فراداده ناموفق بود",
        notificationCueParsing: "در حال پردازش فایل CUE...",
        notificationCueTracksFound: "{count} آهنگ در فایل CUE پیدا شد",
        notificationCuePlaylistCreated: "فهرست پخش از فایل CUE ساخته شد",
        notificationCueNoTracks: "هیچ آهنگ معتبری در فایل CUE پیدا نشد",
        notificationCueParseFailed: "پردازش فایل CUE ناموفق بود",
        notificationLibraryExporting: "در حال برون‌بری کتابخانه...",
        notificationLibraryExported: "کتابخانه در این مسیر برون‌بری شد: {path}",
        notificationExportFailed: "برون‌بری ناموفق بود",
        notificationPlaylistDeleted: "فهرست پخش حذف شد",
        notificationPlaylistDeleteFailed: "حذف فهرست پخش ناموفق بود",
        notificationTrackRemovedFromPlaylist: "آهنگ از فهرست پخش حذف شد",
        notificationTrackRemoveFailed: "حذف آهنگ از فهرست پخش ناموفق بود",
        notificationTrackAddedToPlaylist: "آهنگ به فهرست پخش افزوده شد",
        notificationTrackAlreadyInPlaylist: "آهنگ از قبل در فهرست پخش وجود دارد",
        notificationTrackAddFailed: "افزودن آهنگ به فهرست پخش ناموفق بود",
        notificationUnsupportedFormat: "قالب فایل پشتیبانی نمی‌شود یا فایل خراب است.",
        notificationTrackNotFound: "آهنگ پیدا نشد",
        notificationAudioPlaybackError: "خطا در پخش صدا: {error}",
        notificationNoTrackSelected: "هیچ آهنگی انتخاب نشده است",
        notificationPlaybackNeedsInteraction: "برای شروع پخش ابتدا با برنامه تعامل کنید",
        notificationPlaybackFormatUnsupported: "قالب صوتی پشتیبانی نمی‌شود",
        notificationPlaybackFailed: "پخش ناموفق بود: {error}",
        notificationTrackRemoved: "آهنگ حذف شد",
        notificationConnectionFailed: "اتصال ناموفق بود",
        notificationMoodActivated: "حالت {mood} فعال شد — {count} آهنگ",
        notificationNoMoodTracks: "آهنگی برای حالت {mood} پیدا نشد",
        notificationPlayTrackFirst: "ابتدا یک آهنگ پخش کنید",
        notificationAIAnalyzing: "هوش مصنوعی در حال تحلیل سلیقه شماست...",
        notificationNoAIRecommendations: "هنوز پیشنهادی از هوش مصنوعی نیست. آهنگ‌های بیشتری گوش دهید!",
        notificationAIRecommendationFailed: "دریافت پیشنهاد هوشمند ناموفق بود",
        notificationFindingMusic: "در حال یافتن موسیقی تازه برای شما...",
        notificationNoDiscoveries: "مورد تازه‌ای برای کشف پیدا نشد",
        notificationDiscoveryFailed: "کشف موسیقی ناموفق بود",
        notificationSimilarPlaylistCreated: 'فهرست پخش «{name}» با {count} آهنگ ساخته شد',
        notificationNoSimilarTracks: "آهنگ مشابهی پیدا نشد",
        notificationFavoritesUpdateFailed: "به‌روزرسانی موردعلاقه‌ها ناموفق بود",
        notificationElectronUnavailable: "رابط Electron در دسترس نیست",
        notificationTracksImported: "{count} آهنگ با موفقیت وارد شد.",
        notificationImportFailed: "واردکردن ناموفق بود: {error}",
        notificationScanningFolder: "در حال اسکن پوشه...",
        notificationNoAudioFiles: "در پوشه انتخاب‌شده فایل صوتی پیدا نشد. قالب‌های پشتیبانی‌شده: MP3، WAV، OGG، M4A، FLAC",
        notificationInvalidUrl: "یک نشانی معتبر وارد کنید",
        notificationConfiguringCloud: "در حال آماده‌سازی درخواست ابری...",
        notificationAudioDownloaded: "فایل صوتی با موفقیت دریافت شد",
        notificationRequestFailed: "درخواست ناموفق بود",
        notificationCloudCaptureAborted: "دریافت ابری متوقف شد",
        notificationPlaylistImporting: "در حال واردکردن فهرست پخش...",
        notificationPlaylistImported: 'فهرست پخش «{name}» با {count} آهنگ وارد شد',
        notificationPlaylistImportFailed: "واردکردن ناموفق بود: {error}",
        notificationPlaylistImportError: "خطا در واردکردن",
        notificationDownloadUrlUnavailable: "نشانی دریافت در دسترس نیست",
        notificationNoAudioFilesInPath: "فایل صوتی در این مسیر پیدا نشد: {path}\nقالب‌های پشتیبانی‌شده: MP3، WAV، OGG، M4A، FLAC",
        notificationSystemImportFailed: "واردکردن فایل‌های بازشده از سیستم ناموفق بود",
        notificationInitializationFailed: "راه‌اندازی ناموفق بود",
        notificationDataPathUnavailable: "مسیر پوشه داده در دسترس نیست",
        notificationCannotOpenDirectory: "بازکردن پوشه ممکن نیست",

        // Explorer Page
        explorerSearchPlaceholder: "نام آهنگ، خواننده یا آلبوم را تایپ کنید...",
        explorerSearchBtn: "جستجو",
        explorerNoResults: "نتیجه‌ای یافت نشد",
        explorerSearchHint: "آماده کشف صداهای جدید هستید.",
        explorerSave: "ذخیره",
        explorerSaved: "ذخیره شد",
        explorerImport: "وارد کردن",
        explorerLikedEmpty: "مجموعه شما خالی است",
        explorerLikedEmptyDesc: "کاوش را شروع کنید و آهنگ‌های مورد علاقه خود را ذخیره کنید.",
        explorerFreshDrops: "تازه‌ترین‌ها",
        explorerFreshDropsDesc: "جدیدترین انتشارات و آلبوم‌های داغ روزانه به‌روز می‌شوند.",
        explorerFetching: "دریافت آخرین آهنگ‌ها...",
        explorerComingSoon: "به زودی",
        explorerComingSoonDesc: "این بخش به زودی با نمودارهای زنده پر می‌شود.",
        explorerBrandAttribution: "دانلودها از وب‌سایت MusicDel دریافت می‌شوند.",
        explorerBrand: "KORAI کاوش",
        explorerBack: "بازگشت به پلیر",
        explorerTabExplore: "کاوش",
        explorerTabDiscover: "کشف",
        explorerFavorites: "موردعلاقه‌ها",
        explorerSearchTitle: "جستجو در دنیای موسیقی",
        explorerSearchDesc: "آهنگ‌ها، خواننده‌ها، آلبوم‌ها و فهرست‌های پخش را با کیفیت بالا پیدا کنید.",
        explorerCollectionTitle: "مجموعه شما",
        explorerMusicDelTitle: "موتور MusicDel",
        explorerMusicDelSubtitle: "جستجوی پیشرفته با چند روش",
        explorerClose: "بستن",
        explorerPlayPreview: "پخش یا پیش‌نمایش",
        explorerSongs: "آهنگ‌ها",
        explorerAlbums: "آلبوم‌ها",
        explorerArtists: "خواننده‌ها",
        explorerPlaylists: "فهرست‌های پخش",
        explorerFirstWord: "واژه نخست",
        explorerYourSearch: "جستجوی شما",
        explorerFullTitle: "عنوان کامل",
        explorerNoResultsHint: "املای عبارت را بررسی کنید یا کلیدواژه دیگری را امتحان کنید.",
        explorerSavedTracksCount: "{count} آهنگ ذخیره‌شده",
        explorerResultsCount: "{count} نتیجه یافت شد",
        explorerTracksSelectedCount: "{count} آهنگ برای بخش کشف انتخاب شد",
        explorerNoResultsInColumn: "نتیجه‌ای یافت نشد",
        explorerOnlineSearchUnavailable: "سرویس جستجوی آنلاین در دسترس نیست.",
        explorerDownloadLinkMissing: "پیوند دریافت در صفحه آهنگ پیدا نشد.",
        explorerDownloadPageFailed: "دریافت صفحه آهنگ ناموفق بود: {status}",
        explorerAddTrackFailed: "افزودن آهنگ به کتابخانه ناموفق بود.",
        explorerDownloadShort: "دریافت...",
        explorerUnknownError: "خطای نامشخص",
        explorerSearchDatabase: "در حال جستجو در پایگاه داده...",
        explorerSearchFailed: "جستجو ناموفق بود",
        explorerSearchFailedStatus: "جستجو ناموفق بود ({status})",
        explorerDiscoveryFailedStatus: "کشف ناموفق بود ({status})",
        explorerServerResponseError: "پاسخ سرور با وضعیت {status}",
        explorerSearchQueriesMissing: "عبارت جستجویی در دسترس نیست.",
        explorerAddedFavorite: "به موردعلاقه‌ها افزوده شد",
        explorerRemovedFavorite: "از موردعلاقه‌ها حذف شد",
        explorerRetry: "تلاش دوباره",
        explorerDownloading: "در حال دریافت...",
        explorerAddedLibrary: "به کتابخانه افزوده شد.",
        explorerImportError: "هنگام واردکردن خطایی رخ داد.",
        explorerCheckSpelling: "املای عبارت را بررسی کنید یا کلیدواژه دیگری را امتحان کنید.",
        explorerSearchUnavailable: "جستجو در دسترس نیست",
        explorerTryLater: "بعداً دوباره تلاش کنید یا از جستجوی MusicDel استفاده کنید.",
        explorerDiscoveryBuilding: "در حال ساخت میکس بر اساس سابقه شنیداری شما...",
        explorerNothingToDiscover: "هنوز مورد تازه‌ای برای کشف نیست",
        explorerPlayForDiscovery: "چند آهنگ در KORAI پخش کنید تا میکس شخصی‌سازی‌شده دریافت کنید.",
        explorerDiscoveryWaiting: "صف پیشنهادها منتظر سابقه شنیداری بیشتر است.",
        explorerTracksSelected: "آهنگ برای بخش کشف انتخاب شد",
        explorerDiscoveryUnavailable: "بخش کشف در دسترس نیست",
        explorerLocalServiceUnavailable: "سرویس پیشنهاددهی محلی در دسترس نیست.",
        explorerTryAfterPlayback: "پخش را در KORAI شروع کنید و دوباره تلاش کنید.",

        // ===== Plugin Manager (plugins.html) =====
        pluginStudio: "استودیوی پلاگین",
        pluginPageTitle: "KORAI | استودیوی پلاگین",
        pluginSubtitle: "قابلیت‌های KORAI را با ماژول‌های قدرتمند گسترش دهید",
        pluginTotal: "کل پلاگین‌ها",
        pluginActive: "فعال",
        pluginRunning: "در حال اجرا",
        pluginSearch: "جستجوی پلاگین بر اساس نام یا شناسه...",
        pluginInstall: "نصب پلاگین",
        pluginInstalled: "پلاگین‌های نصب شده",
        pluginPerformance: "عملکرد",
        pluginExit: "بازگشت به پلیر",
        pluginManagement: "مدیریت",
        all: "همه",
        pluginWorking: "در حال انجام...",
        pluginInstalling: "در حال نصب افزونه...",
        pluginTotalHooks: "مجموع هوک‌ها",
        pluginErrors: "خطاها",
        pluginAvgTime: "میانگین زمان هر هوک",
        pluginStats: "آمار افزونه",
        pluginName: "افزونه",
        pluginCalls: "فراخوانی‌ها",
        pluginAvg: "میانگین (میلی‌ثانیه)",
        pluginPerfFailed: "بارگذاری اطلاعات عملکرد ناموفق بود",
        pluginNoDescription: "توضیحی ارائه نشده است.",
        pluginBuiltinCantUninstall: "این افزونه داخلی قابل حذف نیست",
        pluginUninstalling: "در حال حذف...",
        pluginId: "شناسه",
        pluginVersion: "نسخه",
        pluginPath: "مسیر",
        pluginLoadingPerf: "در حال بارگذاری اطلاعات عملکرد...",
        moodTitle: "حال‌وهوا و انرژی",
        aiRecommendTitle: "پیشنهادهای هوشمند",
        recentActivity: "افزوده‌شده‌های اخیر",
        pluginNoPlugins: "هیچ پلاگینی یافت نشد",
        pluginInstallHint: "برای افزایش قابلیت‌های KORAI یک پلاگین نصب کنید",
        pluginEnable: "فعال کردن",
        pluginDisable: "غیرفعال کردن",
        pluginUninstall: "حذف",
        pluginDetails: "جزئیات",
        pluginEnabled: "فعال",
        pluginDisabled: "غیرفعال",
        pluginRunningBadge: "در حال اجرا",
        pluginBuiltin: "پیش‌فرض",
        pluginUninstallConfirm: "آیا از حذف این پلاگین مطمئن هستید؟ این عمل قابل بازگشت نیست.",
        pluginUninstallSuccess: "پلاگین با موفقیت حذف شد",
        pluginUninstallFailed: "خطا در حذف پلاگین",
        pluginToggleSuccess: "وضعیت پلاگین تغییر کرد",
        pluginToggleFailed: "خطا در تغییر وضعیت پلاگین",
        pluginInstallSuccess: "پلاگین با موفقیت نصب شد!",
        pluginInstallFailed: "خطا در نصب پلاگین",
        pluginMissingPermissions: "مجوزهای مورد نیاز موجود نیست",
        pluginLoadingFailed: "خطا در بارگذاری پلاگین‌ها",
        pluginDevKit: "کیت توسعه",
        pluginPerfDashboard: "داشبورد عملکرد"
    }
};



if (typeof window !== 'undefined') {
    window.translations = translations;
}


if (typeof module !== 'undefined' && module.exports) {
    module.exports = translations;
}